[package]
name = "hearthd"
version.workspace = true
edition = "2021"
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = "1"
toml = { workspace = true }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "2"
libc = "0.2"
