[package]
name = "hearthd"
version.workspace = true
edition = "2021"
license.workspace = true

[features]
default = []
systemd = ["dep:libsystemd"]

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ariadne = { workspace = true }
libsystemd = { version = "0.7", optional = true }

[dev-dependencies]
insta = { workspace = true }
tempfile = { workspace = true }
